server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      # 重试次数
      retries: 3
      # 批量发送的消息数量
      batch-size: 16384
      # 32MB的批处理缓冲区
      buffer-memory: 33554432
      # key/value的序列化配置
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: 1
    consumer:
      # 消费者组ID
      group-id: delay-message-group
      # 自动提交offset
      enable-auto-commit: true
      # 自动提交间隔
      auto-commit-interval: 1000
      # key/value的反序列化配置
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # 当没有offset时，从最早的消息开始消费
      auto-offset-reset: earliest
